### ISSUE TITLE
Editing image resolution

### ISSUE THREAD

**Issue by van-ess0** [JohnnieFucker/EarthLive4Mac#1]
Hi, I like your work, but it'd be useful to be able to change picture resolutions. Can you, please, show, where can I set this parameter or just hardcode it with higher res.
Thahk you!

**Comment by JohnnieFucker** [comment]
sorry,you can't change the pic to higher  res.
you can use this pic as background in the center with black background color ,it looks pretty cool.
![image](https://cloud.githubusercontent.com/assets/701244/14006631/43342d82-f1aa-11e5-8b52-cc4e211aead4.png)
